# Generated by Django 4.2.5 on 2023-09-16 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookTime', models.DurationField()),
                ('cookingMethod', models.TextField()),
                ('recipeCategory', models.TextField()),
                ('recipeCuisine', models.TextField()),
                ('recipeYieldAmount', models.IntegerField()),
                ('recipeYieldUnits', models.TextField()),
                ('estimatedCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preformTime', models.DurationField()),
                ('prepTime', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('recipe', models.ManyToManyField(to='cookbook.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unit', models.TextField()),
                ('item', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepNumber', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unit', models.TextField()),
                ('item', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe')),
            ],
        ),
    ]
