# Generated by Django 4.2.5 on 2023-09-16 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='datePublished',
            field=models.DateField(default=datetime.datetime(2023, 9, 16, 4, 38, 45, 912439)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='totalTime',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
