# Generated by Django 4.2.5 on 2023-09-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_recipe_author_recipe_datepublished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeIngredients', to='cookbook.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.TextField(blank=True),
        ),
    ]
