# Generated by Django 4.2.5 on 2023-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_alter_recipeingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
