# Generated by Django 4.2.5 on 2023-09-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeInstructions', to='cookbook.recipe'),
        ),
        migrations.AlterField(
            model_name='recipetool',
            name='recipe',
            field=models.ManyToManyField(related_name='tools', to='cookbook.recipe'),
        ),
    ]
