# Generated by Django 4.2.5 on 2023-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_alter_recipesupply_recipe_alter_recipesupply_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetool',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipetool',
            name='usedInRecipe',
            field=models.ManyToManyField(related_name='toolsUsed', to='cookbook.recipe'),
        ),
    ]
